import type { Client, DashboardData, EmployeePerformance, Invoice, Lead, Metric, ProductionShoot, Task, User } from "./types";
const now=Date.now(); const day=86400000;
export const demoUsers: Record<string,User> = {
 "ceo@agency.local":{id:2,name:"مروان أحمد",email:"ceo@agency.local",role:"ceo",job_title:"CEO"},
 "sales@agency.local":{id:3,name:"سارة محمود",email:"sales@agency.local",role:"sales",job_title:"Senior Sales Executive",target:450000},
 "am@agency.local":{id:4,name:"عمر خالد",email:"am@agency.local",role:"account_manager",job_title:"Account Manager"},
 "creator@agency.local":{id:5,name:"نور علي",email:"creator@agency.local",role:"content_creator",job_title:"Content Creator"},
 "designer@agency.local":{id:6,name:"ليلى حسن",email:"designer@agency.local",role:"designer",job_title:"Senior Designer"},
 "editor@agency.local":{id:7,name:"يوسف سامي",email:"editor@agency.local",role:"video_editor",job_title:"Video Editor"},
 "art@agency.local":{id:8,name:"دينا فؤاد",email:"art@agency.local",role:"art_director",job_title:"Art Director"},
 "production@agency.local":{id:9,name:"كريم عادل",email:"production@agency.local",role:"production",job_title:"Production Lead"},
 "finance@agency.local":{id:10,name:"منى سعيد",email:"finance@agency.local",role:"finance",job_title:"Finance Manager"},
 "quality@agency.local":{id:11,name:"أحمد جلال",email:"quality@agency.local",role:"quality",job_title:"Quality Manager"},
 "hr@agency.local":{id:12,name:"هالة نبيل",email:"hr@agency.local",role:"hr",job_title:"HR Manager"},
};
const clientNames=[["Nova Clinics","Healthcare","#b8ff5a"],["Summit Properties","Real Estate","#7dd3fc"],["Luma Beauty","Beauty","#f9a8d4"],["Vero Coffee","F&B","#e8be8a"],["Orbit Fitness","Fitness","#fb7185"],["Maven Academy","Education","#c4b5fd"],["Aster Tech","Technology","#5eead4"],["Casa Living","Furniture","#e7d7c1"]];
export const mockClients:Client[]=clientNames.map((item,i)=>({id:i+1,name:item[0],industry:item[1],primary_color:item[2],secondary_color:"#111",status:"active",health_score:78+(i*3)%21,contact_name:`Client Contact ${i+1}`,contact_email:`client${i+1}@example.com`,account_manager:demoUsers["am@agency.local"],subscriptions:[{id:i+1,starts_at:"2026-02-01",ends_at:"2027-02-01",status:"active",reels_used:i%6,posts_used:(i*2)%10,stories_used:(i*3)%18,package:{id:(i%3)+1,name:["Launch","Growth","Scale"][i%3],monthly_price:[25000,48000,85000][i%3],reels:[4,8,16][i%3],posts:[8,12,20][i%3],stories:[12,24,40][i%3]}}]}));
const leadStages=["new","contacted","qualified","proposal","negotiation","won","lost"];
export const mockLeads:Lead[]=Array.from({length:28},(_,i)=>({id:i+1,name:["Jane Doe","Darlene Robertson","Wade Warren","Jonah Jude","Peter Thomas","Miriam Fannie","Aisha Hassan"][i%7],company:`Prospect Brand ${i+1}`,email:`lead${i+1}@example.com`,phone:`+20 101 000 ${String(i).padStart(4,"0")}`,source:["Instagram","Referral","Website","LinkedIn"][i%4],stage:leadStages[i%7],temperature:["hot","warm","cold"][i%3] as Lead["temperature"],estimated_value:35000+(i%9)*17000,probability:[10,25,45,65,80,100,0][i%7],next_follow_up_at:new Date(now+(i%7-2)*day).toISOString(),owner:demoUsers["sales@agency.local"]}));
const taskStatuses=["in_progress","waiting_review","need_revision","art_approved","account_review","client_review","client_approved","published","done"];
const taskKinds=[["content","Reel Script","content_creator"],["design","Campaign Key Visual","designer"],["video","Short-form Reel Edit","video_editor"],["design","Social Carousel","designer"],["content","Caption Pack","content_creator"],["production","Product Shoot","production"]] as const;
export const mockTasks:Task[]=Array.from({length:42},(_,i)=>{const kind=taskKinds[i%taskKinds.length]; const email=kind[2]==="designer"?"designer@agency.local":kind[2]==="video_editor"?"editor@agency.local":kind[2]==="production"?"production@agency.local":"creator@agency.local";return {id:i+1,title:`${kind[1]} #${i+1}`,department:kind[0],type:kind[1].toLowerCase().replaceAll(" ","_"),status:taskStatuses[i%taskStatuses.length],priority:["low","medium","high","urgent"][i%4] as Task["priority"],objective:"زيادة التفاعل وتحويل الاهتمام إلى طلب واضح.",buyer_persona:"Urban professionals aged 25–44",platform:["Instagram","TikTok","Facebook","LinkedIn"][i%4],deadline:new Date(now+(i%15-4)*day).toISOString(),client:mockClients[i%mockClients.length],assignee:demoUsers[email],caption:i%3===0?"نسخة تجريبية للكابشن جاهزة للمراجعة والموافقة.":undefined,metadata:{duration:"30 sec",style:"Premium editorial",subtitles:true},versions:i%2===0?[{id:i+1,version:1,path:"/demo-v1.jpg",status:"uploaded",notes:"First creative direction"}]:[]};});
export const mockInvoices:Invoice[]=mockClients.map((c,i)=>({id:i+1,number:`INV-2026-${String(i+1).padStart(4,"0")}`,issue_date:"2026-07-01",due_date:new Date(now+(i%4-1)*7*day).toISOString(),subtotal:[25000,48000,85000][i%3],tax:[3500,6720,11900][i%3],total:[28500,54720,96900][i%3],paid_amount:i%3===0?0:[28500,54720,96900][i%3],status:i%3===0?"unpaid":"paid",client:c}));
export const mockShoots:ProductionShoot[]=mockClients.slice(0,6).map((c,i)=>({id:i+1,title:`${c.name} Content Shoot`,location:["New Cairo Studio","Sheikh Zayed Branch","Client HQ"][i%3],scheduled_at:new Date(now+(i+1)*day).toISOString(),team:["Producer","Photographer","Assistant"],equipment:["Sony FX3","24-70mm","Aputure 600D"],vehicle:"Production Van 01",status:"scheduled",client:c,photographer:demoUsers["production@agency.local"]}));
export const mockEmployees:EmployeePerformance[]=Object.values(demoUsers).filter(u=>!["ceo"].includes(u.role)).map((u,i)=>({...u,tasks_count:18+i*2,completed_count:12+i,late_count:i%4,quality_score:7.5+(i%5)*.5}));
export function mockDashboard(role=demoUsers["ceo@agency.local"].role):DashboardData { const initialMetrics:Metric[]=[{key:"clients",label:"عدد العملاء",value:42,change:8.7},{key:"projects",label:"المشاريع النشطة",value:67,change:12.1},{key:"sales",label:"المبيعات",value:1240000,format:"currency",change:19.3},{key:"collections",label:"التحصيلات",value:980000,format:"currency",change:11.5},{key:"profit",label:"الأرباح",value:465000,format:"currency"},{key:"late",label:"المشاريع المتأخرة",value:7}]; const base={scope:role,metrics:initialMetrics,pipeline:leadStages.map(stage=>({stage,count:mockLeads.filter(l=>l.stage===stage).length,value:mockLeads.filter(l=>l.stage===stage).reduce((a,l)=>a+l.estimated_value,0)})),cash_flow:["Feb","Mar","Apr","May","Jun","Jul"].map((month,i)=>({month,value:220000+i*42000+(i%2?-30000:0)})),tasks:taskStatuses.map(status=>({status,count:mockTasks.filter(t=>t.status===status).length})),review_queue:mockTasks.filter(t=>t.status==="waiting_review"),upcoming:mockTasks.slice(0,8),clients:mockClients.slice(0,6),overdue:mockInvoices.filter(i=>i.status!=="paid"),employees:mockEmployees}; if(role==="sales")base.metrics=[{key:"leads",label:"عدد الـ Leads",value:mockLeads.length,change:12.4},{key:"new",label:"العملاء الجدد",value:9,change:8.1},{key:"deals",label:"قيمة الـ Deals",value:640000,format:"currency",change:18.7},{key:"conversion",label:"Conversion Rate",value:24.8,format:"percent",change:4.2},{key:"target",label:"Target",value:450000,format:"currency"},{key:"achievement",label:"تحقيق التارجت",value:83,format:"percent"}]; if(["designer","video_editor","content_creator","production"].includes(role))base.metrics=[{key:"tasks",label:"مهامي",value:18},{key:"today",label:"تسليم اليوم",value:4},{key:"review",label:"بانتظار المراجعة",value:6},{key:"done",label:"تم هذا الشهر",value:29,change:14}]; if(role==="finance")base.metrics=[{key:"revenue",label:"الإيرادات",value:980000,format:"currency",change:14.2},{key:"expenses",label:"المصروفات",value:515000,format:"currency",change:-3.6},{key:"profit",label:"صافي الربح",value:465000,format:"currency"},{key:"overdue",label:"متأخرات العملاء",value:178000,format:"currency"}]; if(role==="quality")base.metrics=[{key:"quality",label:"Quality Score",value:8.7,format:"score"},{key:"late",label:"Late Tasks",value:7},{key:"completed",label:"Completed Tasks",value:184},{key:"revision",label:"Revision Rate",value:12.4,format:"percent"}]; return base; }
